name: Update Dependencies
on:
  schedule:
    - cron: '0 4 * * MON-FRI'
  workflow_dispatch:
jobs:
  dependency-updates:
    env:
      GIT_USER_NAME: puneetbehl
      GIT_USER_EMAIL: behlp@objectcomputing.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Export Gradle Properties
        uses: micronaut-projects/github-actions/export-gradle-properties@master
      - name: Check Dependencies
        run: ./gradlew useLatestVersions
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          committer: ${{ env.GIT_USER_NAME }} <${{ env.GIT_USER_EMAIL }}>
          author: ${{ env.GIT_USER_NAME }} <${{ env.GIT_USER_EMAIL }}>
          commit-message: Update dependencies
          title: 'Dependency upgrades'
          body: Upgrades dependencies to their latest versions
          labels: "type: dependency-upgrade"
          base: ${{ env.githubBranch }}
          branch: dependency-updates
